### ISSUE TITLE
TableFooter could  use <tfoot> ?

### ISSUE THREAD

**Issue by Glidias** [estevanmaito/windmill-react-ui#73]
### Reproduction:

Run <`TableFooter>` within `<Table>`.

### Problem description:

```
index.js:1 Warning: validateDOMNesting(...): <div> cannot appear as a child of <tfoot>.
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:4627:21
    at tfoot
    at table
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:4340:21
    at div
```

### Suggested solution:

Use `<tfoot>` element instead of plain div element for TableFooter component.

**Comment by narimanb** [comment]
> 

Changed from `<div>` to `<tfoot>`.  [https://github.com/narimanb/wreactui](https://github.com/narimanb/wreactui)

**Comment by Glidias** [comment]
Actually, according to the documentation under` <TableFooter>`, it could be a generic `<div>` since it can be placed under TableContainer as in the example https://windmillui.com/react-ui/components/table#table-footer

However, it would be good if there was an option to choose  tag between `"div" | "tfoot"` tag as that might come in useful depending on where you're placing it. Besides `"div"`, may even `| "footer"` for html5 sementic-preference.
